version: 2.1
orbs:
  npm-config: cobli/npm-config@1.0.0
jobs:
  install_using_gh_packages:
    docker:
      - image: 'cimg/node:17.8.0'
    steps:
      - checkout
      - npm-config/set-registry:
          registry-prurl: //npm.pkg.github.com/
          scope: '@compeydev'
          auth-token: $GH_TOKEN
      - run:
          name: Install pkg
          command: npm install @compeydev/musiccomp-discord-bot
  pull_docker_image:
    docker:
      - image: 'cimg/node:17.8.0'
    steps:
      - checkout
      - setup_remote_docker: 
          version: 19.03.13      
      - run:
          name: Pull docker image
          command: docker pull compey/musiccomp-discord-bot:0.2.13  

      - run: 
          name: Authorize into GitHub Container Registry
          command: echo $CR_PAT | docker login ghcr.io -u $CR_USERNAME --password-stdin

      - run: 
          name: Pull docker image from GitHub Container Registry
          command: docker pull ghcr.io/compeydev/musiccomp-discord-bot:latest


workflows:
  install:
    jobs:
      - install_using_gh_packages
      - pull_docker_image
