version: 2.1
orbs:
  npm-config: cobli/npm-config@1.0.0
jobs:
  build_and_test:
    docker:
      - image: 'circleci/node:9.11.2'
    steps:
      - checkout
      - npm-config/set-registry:
          registry-prurl: //npm.pkg.github.com/
          scope: '@compeydev'
          auth-token: $GH_TOKEN
      - run:
          name: Install pkg
          command: npm install @compeydev/musiccomp-discord-bot@0.2.13-ghp
