name: CI

on: [push]

jobs:
  Install_Packages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
 #   - uses: egordm/gha-yarn-node-cache@v1
 #   - name: Install JS dependencies
  #    run: yarn install
 #   - name: Test
#      run: yarn test
    - name: Install package using npm
      run: npm install musiccomp-discord-bot
    - name: Install package using yarn
      run: yarn add musiccomp-discord-bot
    - run: |
        npm install @compeydev/musiccomp-discord-bot
    - env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Results
      run: echo "This job's status is ${{ job.status }}."
