name: Deploy Docs

on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install deps
      run: cd site && npm install
    - name: Build
      run: cd site ; npm run build ; cd build ; mv * /home/runner/work/MusicComp-v2/MusicComp-v2/docs/docs
    - name: Commit and push if there are changes
      run: |-
        git config --global user.email "hi@devcomp.tk"
        git config --global user.name "CompeyDev"
        git add -A
        git commit -m "Deploy Documentation"
        git push
