name: Packages

on:
  [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  gh_pkg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1    
    - run: |
        npm install @compeydev/musiccomp-discord-bot@0.2.13-ghp
