name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: egordm/gha-yarn-node-cache@v1
    - name: Checkout code
      run: checkout
    - name: Install JS dependencies
      run: yarn install
    - name: Test
      run: yarn test
    - name: Build
      run: yarn build
    - run: echo "This job's status is ${{ job.status }}."
