name: CI

on: [push]

jobs:
  Install_Packages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install package using npm
      run: npm install musiccomp-discord-bot
    - name: Install package using yarn
      run: yarn add musiccomp-discord-bot
    - name: Results
      run: echo "This job's status is ${{ job.status }}."
